services:
  - type: web
    name: skillflash-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: development
      - key: URI
        sync: false
